### ISSUE TITLE
how to conda install AmberTools

### ISSUE THREAD

**Issue by dacase** [Amber-MD/setup-scripts#2] opened 2016-12-10 16:06 UTC
OK: I have a bare Ubuntu VirtualBox image.
I ran "bash install_python.sh" and updated my PATH variable.

How do I proceed to do something like "conda install AmberTools"?  I just want to get a binary
distribution (i.e. assuming I am a user, not a developer)

I've been searching through my emails, but don't really know which suggestion to try.  The proposed command "conda install -c hainm ambertools=16" says it is for python 3.5, but I'd like to get a python 2.7 installation, since that is what users probably want in practice right now.

**Comment by hainm** [comment] 2016-12-10 16:22
That is my intention to hide since we do not have and official build yet. I will do some checking and reply later (this afternoon).

**Comment by dacase** [comment] 2016-12-10 17:03
No rush....I can wait, and will probably be busy later today anyway.

**Comment by hainm** [comment] 2016-12-10 19:42
@dacase 

Please try again

```bash
conda install -c hainm ambertools=16
```

that's it. 

- log
```bash
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ambertools-16.20           |           py27_1        74.3 MB  hainm
```

-  try
```bash
 $ tleap
-I: Adding /home/haichit/anaconda3/envs/py2/dat/leap/prep to search path.
-I: Adding /home/haichit/anaconda3/envs/py2/dat/leap/lib to search path.
-I: Adding /home/haichit/anaconda3/envs/py2/dat/leap/parm to search path.
-I: Adding /home/haichit/anaconda3/envs/py2/dat/leap/cmd to search path.

Welcome to LEaP!
(no leaprc in search path)
>
```

**Comment by dacase** [comment] 2016-12-11 02:31
Works for me!  Can we try to get xleap?  Would also be good to include a copy of Amber16.pdf.

I'm also going to try to get some agreement on things we might leave out (even of the official AmberTools17): high on my personal list are mm_pbsa, mtkpp, nmode (only used by mm_pbsa, I think).

Great job!

**Comment by swails** [comment] 2016-12-11 03:25
If you leave out mm_pbsa, FEW will be hobbled.

**Comment by swails** [comment] 2016-12-11 03:26
Also, how does AMBERHOME get set?

**Comment by hainm** [comment] 2016-12-11 03:56
> Also, how does AMBERHOME get set?

similar to your bash script but using python (Dave likes Python now, :x). Please check here: https://github.com/Amber-MD/ambertools-conda-build/blob/master/recipe/patch_amberhome/copy_and_post_process_bin.py
It checks (blindly) any executable files having `AMBERHOME` word to make dispatch script.

> If you leave out mm_pbsa, FEW will be hobbled.

:D I did not have tested conda build for ambertools yet. Try to hide it but Dave requested. :D

**Comment by hainm** [comment] 2016-12-11 03:59
> Can we try to get xleap?
yeah, let me check if we can do it first.

>  Would also be good to include a copy of Amber16.pdf.
yeah.

> I'm also going to try to get some agreement on things we might leave out (even of the official AmberTools17): high on my personal list are mm_pbsa, mtkpp, nmode (only used by mm_pbsa, I think).

It's not hurt to include them. I think "nmode" is useful for some users from recent emails in maillist.
But we definitely exclude some.

**Comment by swails** [comment] 2016-12-11 04:38
+1 for excluding nmode.  The nmode capabilities of nab are far superior (e.g., GB support), and the only missing feature (decomposition) is almost never used, and it's not entirely clear if it's even useful.

The benefit to excluding them is that we get to stop supporting that which does not get released.

**Comment by hainm** [comment] 2016-12-11 04:41
oh, I never realize that `nab` does `nmode` too. yeah, +1 too.

**Comment by hainm** [comment] 2016-12-11 06:24
@dacase 

done. Please try
```bash
conda upgrade ambertools
```

- [x] xleap: installed but not sure if it work correctly. Please try and look at the dispatch script too. https://github.com/Amber-MD/ambertools-conda-build/blob/master/recipe/patch_amberhome/xleap
- [x] Amber16.pdf: in `$PREFIX/doc/` where PREFIX=sys.prefix
- [x] add amber registration too (no push request to ambermd, just a demo for practising)
- [ ] nab does not works yet

**Comment by hainm** [comment] 2016-12-12 02:50
I can confirm that `xleap` does work.

**Comment by dacase** [comment] 2016-12-12 15:29
"conda upgrade ambertools" doesn't work for me.  Just says
"all requested packages already installed", and does not load xleap, or Amber16.pdf.

**Comment by hainm** [comment] 2016-12-12 15:43
Can you try adding 

--force

Hai Nguyen

**Comment by hainm** [comment] 2016-12-12 15:46
Or

conda install -c hainm ambertools --force

I've tried yesterday in bash on windows and there is xleap and it works (saw its gui)

**Comment by hainm** [comment] 2016-12-12 16:26
PS: I only update the content of ambertools tar file without updating its version number, that's why the `upgrade` did not work (will keep in mind this).

**Comment by dacase** [comment] 2016-12-12 16:45
adding "--force" to conda upgrade did not work, but adding it to "conda install ..." did work

**Comment by hainm** [comment] 2016-12-12 16:53
thanks.

I just
- update install guide: https://github.com/Amber-MD/setup-scripts#install-ambertools
- also add travis integration for those guides to make sure it always work (as an user):  https://travis-ci.org/Amber-MD/setup-scripts/builds/183158327

**Comment by hainm** [comment] 2017-01-11 01:21
I think we can close this issue now.

**Closed by hainm** 2017-01-11 01:21 UTC
